/*
 * I2C_Interface.h
 *
 *  Created on: Feb 22, 2021
 *      Author: mica
 */

#ifndef MCAL_I2C_I2C_INTERFACE_H_
#define MCAL_I2C_I2C_INTERFACE_H_

//CONFIGURATION FOR MASTERS TRANSMITTER OR RECEIVER
#define IIC_START_TRANSMITTED_MASTER         (0X08)
#define IIC_REP_START_TRANSMITTED_MASTER     (0X10)

#define IIC_SLA__W_TRANSMITTED_ACK_MASTER    (0X18)
#define IIC_SLA__W_TRANSMITTED_NACK_MASTER   (0X20)

#define IIC_SLA__R_TRANSMITTED_ACK_MASTER    (0X40)
#define IIC_SLA__R_TRANSMITTED_NACK_MASTER   (0X48)

#define IIC_DATA_TRANSMITTED_ACK_MASTER      (0X28)
#define IIC_DATA_TRANSMITTED_NACK_MASTER     (0X30)

#define IIC_MASTER_LOST_ARBITTRATION_MASTER  (0X38)//LOST IN SLA+W OR DATA(FOR MASTER TRANSMITTER) // SLA+R OR NACK (FOR MATER RECEIVER)


#define IIC_DATA_RECEIVED_ACK_MASTER         (0X50)
#define IIC_DATA_RECEIVED_NACK_MASTER        (0X58)




//CONFIGURATION FOR SLAVE TRANSMITTER OR RECEIVER

#define IIC_SLA__W_RECEIVED_ACK_SLAVE          (0X60)

#define IIC_SLA__R_RECEIVED_ACK_SLAVE          (0XA8)

#define IIC_DATA_TRANSMITTED_ACK_SLAVE         (0XB8)
#define IIC_DATA_TRANSMITTED_NACK_SLAVE        (0XC0)

#define IIC_LAST_DATA_TRANSMITTED_ACK_SLAVE    (0XC8)



#define IIC_GENERAL_CALL_ADDRESS_RECEIVED_ACK_SLAVE    (0X70)

#define IIC_DATA_RECEIVED_NACK_THIS_ADDRESSED_WITH_GENERAL_CALL_SLAVE    (0X98)
#define IIC_DATA_RECEIVED_ACK_THIS_ADDRESSED_WITH_GENERAL_CALL_SLAVE    (0X90)

#define IIC_DATA_RECEIVED_NACK_THIS_ADDRESSED_WITH_SLA_W_SLAVE    (0X88)
#define IIC_DATA_RECEIVED_ACK_THIS_ADDRESSED_WITH_SLA_W_SLAVE    (0X80)

#define IIC_MASTER_LOST_ARBITTRATION_MASTER (0X38)//LOST IN SLA+W OR DATA(FOR MASTER TRANSMITTER) // SLA+R OR NACK (FOR MATER RECEIVER)






void IIC_void_Init_Master(void);
void IIC_void_Init_Slave(void);
void IIC_void_Start (void);
void IIC_void_Stop(void);
void IIC_void_Write(u8 data);
u8 IIC_u8_ReadAck(void);
u8 IIC_u8_ReadNAck(void);

u8 IIC_u8_ReadStatus(void);

#endif /* MCAL_I2C_I2C_INTERFACE_H_ */
